name: App Build and Deploy
on:
  push:
    paths:
      - 'app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          cd app
          docker build -t wiz-app .
